apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus_ds
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: false

  - name: Jaeger
    uid: jaeger_ds
    type: jaeger
    url: http://jaeger:16686
    access: proxy
    editable: false
